services:
  api:
    build:
      context: api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8000
    networks:
      - contacts-backend
      - mydb

  frontend-contacts:
    build: frontend-contacts
    volumes:
      - vue-dist:/dist

volumes:
  vue-dist:

networks:
  contacts-backend:
    external: true
  mydb:
    external: true