services:
  api:
    build:
      context: api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8000
    networks:
      - contacts-backend
      - mydb
    env_file:
      - path: ./api/.env
        required: true

  frontend-contacts:
    build: frontend-contacts
    volumes:
      - contacts-dist:/dist

volumes:
  contacts-dist:
    name: contacts-dist
    external: true

networks:
  contacts-backend:
    external: true
  mydb:
    external: true