services:
  api:
    build:
      context: api
    restart: always
    secrets:
      - db-password
    environment:
      - ASPNETCORE_URLS=http://+:8000

  frontend-contacts:
    build: frontend-contacts
    ports:
      - 80:80
    depends_on:
      - api

secrets:
  db-password:
    file: db/password.txt