services:
  api:
    build:
      context: api
    restart: always
    secrets:
      - db-password
    # depends_on:
    #   db:
    #     condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8000
    networks:
      - contacts-backend

  frontend-contacts:
    build: frontend-contacts
    volumes:
      # - ./frontend-contacts/dist:/dist
      - vue-dist:/dist

volumes:
  vue-dist:

secrets:
  db-password:
    file: db/password.txt

networks:
  contacts-backend:
    external: true